#+OPTIONS: toc:nil

* A brief trip back to 6th grade math
  :PROPERTIES:
  :CUSTOM_ID: a-brief-trip-back-to-6th-grade-math
  :END:

If you've ever heard that programming and math are related, that's
because they are. Though you make the computer do all the actual math
for you so don't let that scare you.

In school when you started basic algebra which introduced "variables" So
you could write an expression like: x + 10 then if I told you that x = 2
you would know that this expression solves to 12. Here we used x as a
placeholder value and in programming we do the same thing.

Variables in programming are easier to reason about if you think of them
like buckets. When you make a variable you're creating a bucket and
labeling it so you can reference it's contents later.

To declare a variable in Python you simply type:

#+BEGIN_EXAMPLE
    >>> variable = 10
#+END_EXAMPLE

Now if you type:

#+BEGIN_EXAMPLE
    >>> variable + 10
#+END_EXAMPLE

You should see 20 printed to the screen, see how it works?

The cool thing about variables in programming is that they can hold more
than just numbers, now would be a good time to talk about Data Types.
